version: '3'

services:
  db:
    image: mysql
    networks:
      - backnet
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development
  web:
    build: ./web
    entrypoint: dockerize -wait tcp://db:3306 --timeout 30s docker-entrypoint.sh
    volumes:
      - ./web:/usr/app
    networks:
      - backnet
    command: node /usr/app/src/index.js
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    networks:
      - backnet
    ports:
    - "80:80"
    depends_on:
      - web

networks:
  backnet:
    driver: bridge
